In [11]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder, OneHotEncoder, MinMaxScaler, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

# Load dataset
df = pd.read_csv('C:\\Users\\DivyaTejAtluri\\Downloads\\employee_productivity_dataset.csv')

# Display first rows
df.head()

,Employee_ID,Name,Department,Age,Gender,Work_Mode,Join_Date,Hours_Worked_Per_Week,Projects_Completed,Performance_Score,Salary,Location
0,E001,Amit Sharma,IT,25.0,Male,Remote,15-01-2021,40.0,5,4.5,50000.0,Pune
1,E002,Riya Patel,HR,30.0,Female,Hybrid,15-02-2020,38.0,4,4.0,45000.0,Mumbai
2,E003,John Mathew,Finance,NaN,Male,Onsite,10-03-2022,45.0,6,NaN,60000.0,Bangalore
3,E004,Sneha Joshi,IT,28.0,Female,Remote,22-04-2021,NaN,5,4.2,52000.0,Delhi
4,E005,Arjun Verma,Marketing,35.0,Male,Hybrid,18-05-2020,50.0,7,4.8,NaN,Pune

Q1. Handle Missing Values (Basic Cleaning)

Fill missing values using the following:

Age → Median

Salary → Mean

Hours_Worked_Per_Week → Median

Performance_Score → Mean

Display the dataset after handling missing values

In [12]:
df['Age'].fillna(df['Age'].median())
df['Salary'].fillna(df['Salary'].mean())
df['Hours_Worked_Per_Week'].fillna(df['Hours_Worked_Per_Week'].median())
df['Performance_Score'].fillna(df['Performance_Score'].mean())

df.head()

,Employee_ID,Name,Department,Age,Gender,Work_Mode,Join_Date,Hours_Worked_Per_Week,Projects_Completed,Performance_Score,Salary,Location
0,E001,Amit Sharma,IT,25.0,Male,Remote,15-01-2021,40.0,5,4.5,50000.0,Pune
1,E002,Riya Patel,HR,30.0,Female,Hybrid,15-02-2020,38.0,4,4.0,45000.0,Mumbai
2,E003,John Mathew,Finance,NaN,Male,Onsite,10-03-2022,45.0,6,NaN,60000.0,Bangalore
3,E004,Sneha Joshi,IT,28.0,Female,Remote,22-04-2021,NaN,5,4.2,52000.0,Delhi
4,E005,Arjun Verma,Marketing,35.0,Male,Hybrid,18-05-2020,50.0,7,4.8,NaN,Pune

Q2. Label Encoding

Convert these columns into numeric values using Label Encoding:

Gender

Department

Show the updated columns

In [13]:
le = LabelEncoder()

df['Gender'] = le.fit_transform(df['Gender'])
df['Department'] = le.fit_transform(df['Department'])

df[['Gender', 'Department']].head()

   Gender  Department
0       1           2
1       0           1
2       1           0
3       0           2
4       1           3

Q3. One-Hot Encoding

Apply One-Hot Encoding on:

Work_Mode

Location

Display the dataset and check how many new columns are created.

In [14]:
df = pd.get_dummies(df, columns=['Work_Mode', 'Location'])

df.head()
print("Total columns after encoding:", df.shape[1])

Total columns after encoding: 17

Q4. Normalization (Min-Max Scaling)

Normalize the following columns:

Salary

Hours_Worked_Per_Week

Use MinMaxScaler and display results.

In [15]:
scaler = MinMaxScaler()

df[['Salary', 'Hours_Worked_Per_Week']] = scaler.fit_transform(
    df[['Salary', 'Hours_Worked_Per_Week']]
)

df[['Salary', 'Hours_Worked_Per_Week']].head()

     Salary  Hours_Worked_Per_Week
0  0.347826               0.285714
1  0.130435               0.142857
2  0.782609               0.642857
3  0.434783                    NaN
4       NaN               1.000000

Q5. Standardization (Scaling)

Apply StandardScaler on:

Age

Projects_Completed

Display the transformed values.

In [16]:
scaler_std = StandardScaler()

df[['Age', 'Projects_Completed']] = scaler_std.fit_transform(
    df[['Age', 'Projects_Completed']]
)

df[['Age', 'Projects_Completed']].head()

        Age  Projects_Completed
0 -1.140068           -0.211604
1 -0.024784           -0.916949
2       NaN            0.493742
3 -0.470898           -0.211604
4  1.090500            1.199088

Q6. Compare Scaling Methods

Apply both:

MinMaxScaler

StandardScaler

On the Salary column.

Show both results side by side.

In [17]:
salary = df[['Salary']]

minmax = MinMaxScaler().fit_transform(salary)
standard = StandardScaler().fit_transform(salary)

comparison = pd.DataFrame({
    'Original': salary.values.flatten(),
    'MinMax': minmax.flatten(),
    'Standardized': standard.flatten()
})

comparison.head()

   Original    MinMax  Standardized
0  0.347826  0.347826     -0.092450
1  0.130435  0.130435     -0.785825
2  0.782609  0.782609      1.294300
3  0.434783  0.434783      0.184900
4       NaN       NaN           NaN

Q7. Build Preprocessing Pipeline

Create a pipeline that:

Applies encoding to categorical columns

Applies scaling to numerical columns

Use:

ColumnTransformer

Pipeline

In [19]:
num_cols = ['Age', 'Salary', 'Hours_Worked_Per_Week', 'Projects_Completed']
cat_cols = ['Gender', 'Department', 'Work_Mode', 'Location']

preprocessor = ColumnTransformer([
    ('num', StandardScaler(), num_cols),
    ('cat', OneHotEncoder(), cat_cols)
])

pipeline = Pipeline([
    ('preprocessing', preprocessor)
])

pipeline.named_steps['preprocessing']

pipeline

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['Age', 'Salary',
                                                   'Hours_Worked_Per_Week',
                                                   'Projects_Completed']),
                                                 ('cat', OneHotEncoder(),
                                                  ['Gender', 'Department',
                                                   'Work_Mode',
                                                   'Location'])]))])

Q8. Apply Pipeline

Apply the pipeline on the dataset.

Display:

Transformed dataset

Shape of final dataset

In [20]:
df_original = pd.read_csv('C:\\Users\\DivyaTejAtluri\\Downloads\\employee_productivity_dataset.csv')

transformed_data = pipeline.fit_transform(df_original)

print("Shape of transformed data:", transformed_data.shape)

Shape of transformed data: (250, 17)